version: '3.5'
services:
  postgres:
    hostname: postgres
    image: library/postgres:12-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pgdata:/data/postgres
    ports:
      - 5432:5432
    networks:
      - backend
  jupyter:
    hostname: jupyter
    build:
      context: jupyter
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - ./notebooks:/root/airflow/notebooks
networks:
  backend:
    driver: bridge