providers:
  file:
    filename: /traefik.yml
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedbydefault: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: root@insrt.ru
      storage: /ssl/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: DEBUG

http:
  routers:
#    front:
#      entryPoints:
#        - "web"
#        - "https"
#      rule: "Host(`investhelper.insrt.ru`)"
#      service: front-srv
#      tls:
#        certResolver: myresolver
#      priority: 26
    app:
      entryPoints:
        - "web"
        - "https"
      rule: "Host(`investhelper.insrt.ru`)"
      service: app-srv
      tls:
        certResolver: myresolver
      priority: 33
  services:
    app-srv:
      loadBalancer:
        servers:
          - url: http://nginx:8080
#    front-srv:
#      loadBalancer:
#        servers:
#          - url: http://front:80
